substitutions:
  device_name: logicpower-ups
  friendly_name: LogicPower UPS
  ap_ssid: AP-LogicPower
  ap_password: password
  time_zone: Europe/Kyiv
  wifi_rssi_update: 60s
  ups_tx_pin: GPIO17
  ups_rx_pin: GPIO16
  ups_baud_rate: "2400"
  ups_update_interval: 5s

esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}
  project:
    name: syssi.esphome-pipsolar
    version: "322e2b2"

esp32:
  board: esp32dev
  framework:
    type: esp-idf

packages:
  common: !include logicpower-ups-common.yaml
  pip8048: !include logicpower-ups-syssi-pip8048.yaml

api:
  reboot_timeout: 0s
